name: Build And Push Docker Image

on:
  push:
    paths-ignore:
      - "*.md"
    branches:
      - "master"
      - "develop"
  workflow_dispatch:

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # - uses: pixta-dev/repository-mirroring-action@v1
      #   with:
      #     target_repo_url: git@gitlab.com:icocoding/qinglong.git
      #     ssh_private_key: ${{ secrets.GITLAB_SSH_PK }}

  release-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: "8.3.1"

      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"

      - name: build front and back
        id: build_front_and_back
        run: |
          pnpm install --frozen-lockfile
          pnpm build:front
          pnpm build:back
          ls static
          echo "::set-output name=STATIC_PATH::$(pwd)/static"
          changeLog=$(awk '/changeLog: \|/ {f=1;next} f {print; if (/^[[:space:]]*3\./) exit}' version.yaml | sed 's/^[[:space:]]*//')
          echo "::set-output name=CHANGE_LOG::${changeLog}"
          tag_name=$(cat version.yaml | grep 'version:' | awk '{print $2}')
          echo "::set-output name=PUBLISH_TAG_NAME::${tag_name}"

      - name: Zip the file
        id: zip_static
        run: |
          STATIC_PATH=${{ steps.build_front_and_back.outputs.STATIC_PATH }}
          zip -r qinglong_static.zip ${STATIC_PATH}/*
          
          echo "::set-output name=ZIP_FILE_PATH::$(pwd)/qinglong_static.zip"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.build_front_and_back.outputs.PUBLISH_TAG_NAME }}
          release_name: Release ${{ steps.build_front_and_back.outputs.PUBLISH_TAG_NAME }}
          draft: true
          prerelease: true
          body: ${{ steps.build_front_and_back.outputs.CHANGE_LOG }}

      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.zip_static.outputs.ZIP_FILE_PATH }}
          asset_name: qinglong_static.zip
          asset_content_type: application/zip

      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
    
