name: Build And Push Docker Image

on:
  push:
    paths-ignore:
      - "*.md"
    branches:
      - "master"
      - "develop"
  workflow_dispatch:

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # - uses: pixta-dev/repository-mirroring-action@v1
      #   with:
      #     target_repo_url: git@gitlab.com:icocoding/qinglong.git
      #     ssh_private_key: ${{ secrets.GITLAB_SSH_PK }}

  release-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: "8.3.1"

      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"

      - name: build front and back
        run: |
          pnpm install --frozen-lockfile
          pnpm build:front
          pnpm build:back

      - uses: actions/checkout@v2
        id: zip_static
      - name: Zip the file
        run: |
          zip -r qinglong_static.zip static
          echo "::set-output PUBLISH_NOTE=$(cat version.yaml)::"
          echo "::set-output TAG_NAME=$(date +'%Y%m%d%H%M%S')::"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.zip_static.outputs.TAG_NAME }}
          release_name: Release ${{ steps.zip_static.outputs.TAG_NAME }}
          draft: true
          prerelease: false
          body: |
            ${{ steps.zip_static.outputs.PUBLISH_NOTE }}

      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./qinglong_static.zip
          asset_name: qinglong_static.zip
          asset_content_type: application/zip

      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
    
